version: '3.7'
services:
 hotel-management-db:
    image: mysql:8.0.25
    container_name: hotel-management-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/database/data:/var/lib/mysql
    networks:
      - hotel-management-network
 hotel-management-db-gui-admin:
    image: phpmyadmin/phpmyadmin
    container_name: hotel-management-db-gui-admin
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
    environment:
      PMA_HOST: hotel-management-db
      UPLOAD_LIMIT: 300M
    networks:
      - hotel-management-network
networks:
  hotel-management-network:
    driver: bridge